### ISSUE TITLE
Clean Up Build Script

### ISSUE THREAD

**Issue by xavierholt** [UCSB-CS56-Projects/cs56-games-checkers#17]
There's a bunch of stuff in `build.xml` that can be cleaned up:
 - Remove the obsolete tasks (probably `download`, `publish`, and `linenumbers`).
 - Remove any unused properties.
 - Add descriptions for the "public" tasks (the ones you'd use from the command line).
 - Clean up the bad indentation and trailing spaces (try `xmllint --format`?).

50 XP

**Comment by aryamandas** [comment]
W18 OK (50 points)
