### ISSUE TITLE
findCoordinates function in checkersBoard

### ISSUE THREAD

**Issue by athielk** [UCSB-CS56-Projects/cs56-games-checkers#3]
Do we need a for loop here or is there some way to convert s to an int?
`for(int i = 0; i < 32; i++){
            if(s.equals(coordinates.get(i))){
                return i;
            }`

**Comment by athielk** [comment]
F16 OK (100pts)

**Comment by xavierholt** [comment]
If you want to do this right, see https://github.com/UCSB-CS56-Projects/cs56-games-checkers/issues/20 (it's big!).

Reducing the points on this one:
50 XP

**Comment by xavierholt** [comment]
Fixed in https://github.com/UCSB-CS56-Projects/cs56-games-checkers/issues/20.

+50 XP
