### ISSUE TITLE
Add Basic AI

### ISSUE THREAD

**Issue by gmfoster** [UCSB-CS56-Projects/cs56-games-checkers#30]
Add a basic AI that will allow the player to play vs the computer
500 pts

**Comment by xavierholt** [comment]
Basic version (200 XP):  The "AI" makes a random valid move.

Advanced version (more points - talk to your mentor):  Make it choose the "best" move based on some heuristics.

F17 OK: 200+ XP

**Comment by aryamandas** [comment]
W18 OK (200 pts)
