### ISSUE TITLE
Wheres checkerpeices

### ISSUE THREAD

**Issue by athielk** [UCSB-CS56-Projects/cs56-games-checkers#4]
Right now checkerboard is handling all the pieces and where they can move.  Instead abstract the pieces out by making them their own class and simplify the board down to just hold them and who's turn it is.

**Comment by athielk** [comment]
F16 OK (200 pts)

**Comment by athielk** [comment]
To help guide you so that it is easier to add features in the future.  What is the difference between a chess board and a checkers board?

**Comment by aryamandas** [comment]
W18 OK (200 pts)
